#!/bin/bash
# Quick start script for running on instance

# Simple one-liner to get started
echo "🚀 Quick Start Commands for Instance Deployment"
echo "=============================================="
echo ""
echo "1️⃣ Automated deployment (from local machine):"
echo "   ./deploy_to_instance.sh ubuntu YOUR_INSTANCE_IP"
echo ""
echo "2️⃣ Quick test with single container (on instance):"
echo "   docker run -d --name test-extractor \\"
echo "     -e CONTAINER_ID=1 \\"
echo "     -e URL_CHUNK_START=0 \\"
echo "     -e URL_CHUNK_SIZE=20 \\"
echo "     -v \$(pwd)/data:/app/data \\"
echo "     1stdibs-extractor"
echo ""
echo "3️⃣ Production run with 10 containers (on instance):"
echo "   for i in {1..10}; do"
echo "     docker run -d --name extractor-\$i \\"
echo "       -e CONTAINER_ID=\$i \\"
echo "       -e URL_CHUNK_START=\$(( (\$i - 1) * 5000 )) \\"
echo "       -e URL_CHUNK_SIZE=5000 \\"
echo "       -v \$(pwd)/data/container\$i:/app/data \\"
echo "       1stdibs-extractor"
echo "   done"
echo ""
echo "4️⃣ Monitor all containers:"
echo "   watch -n 5 'docker ps --filter name=extractor'"
echo ""
echo "5️⃣ Get notifications on your phone:"
echo "   # Install ntfy.sh app and subscribe to: 1stdibs-extraction-1"
echo ""
echo "6️⃣ Check results:"
echo "   find data -name '*.json' | wc -l  # Count extracted products"
echo "   tail -f data/container1/logs/extraction.log  # View logs"